// Package langfuse generates Docker Compose configuration for self-hosted Langfuse.
// Langfuse provides LLM execution trace visualization for agent observability.
package langfuse

import (
	"fmt"
	"strings"
	"text/template"
)

// Config holds parameters for Langfuse Docker Compose generation.
type Config struct {
	// Port is the Langfuse web UI port. Default: 3100.
	Port int
	// PostgresPort is the Langfuse Postgres port. Default: 5433 (avoids conflict with user's Postgres).
	PostgresPort int
	// AgentName is the project/agent name for labeling.
	AgentName string
	// OTelEndpoint is the OTLP endpoint if OTel collector is also deployed.
	OTelEndpoint string
}

const composeTemplate = `# Auto-generated by volra — Langfuse self-hosted configuration
# Provides LLM execution trace visualization for {{.AgentName}}

services:
  langfuse-db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: langfuse
      POSTGRES_PASSWORD: langfuse
      POSTGRES_DB: langfuse
    volumes:
      - langfuse-db-data:/var/lib/postgresql/data
    ports:
      - "{{.PostgresPort}}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U langfuse"]
      interval: 5s
      timeout: 3s
      retries: 5

  langfuse:
    image: langfuse/langfuse:2
    restart: unless-stopped
    depends_on:
      langfuse-db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://langfuse:langfuse@langfuse-db:5432/langfuse"
      NEXTAUTH_URL: "http://localhost:{{.Port}}"
      NEXTAUTH_SECRET: "volra-langfuse-secret-change-in-production"
      SALT: "volra-langfuse-salt-change-in-production"
      TELEMETRY_ENABLED: "false"
    ports:
      - "{{.Port}}:3000"

volumes:
  langfuse-db-data:
`

// RenderCompose generates the Docker Compose YAML for Langfuse services.
func RenderCompose(cfg Config) (string, error) {
	if cfg.Port == 0 {
		cfg.Port = 3100
	}
	if cfg.PostgresPort == 0 {
		cfg.PostgresPort = 5433
	}

	tmpl, err := template.New("langfuse-compose").Parse(composeTemplate)
	if err != nil {
		return "", fmt.Errorf("parsing langfuse compose template: %w", err)
	}

	var buf strings.Builder
	if err := tmpl.Execute(&buf, cfg); err != nil {
		return "", fmt.Errorf("rendering langfuse compose: %w", err)
	}
	return buf.String(), nil
}

// DashboardURL returns the Langfuse dashboard URL for the given configuration.
func DashboardURL(port int) string {
	if port == 0 {
		port = 3100
	}
	return fmt.Sprintf("http://localhost:%d", port)
}
