// Package alerting generates Alertmanager and Prometheus alerting configurations.
package alerting

import (
	"fmt"
	"strings"
	"text/template"

	"github.com/romerox3/volra/internal/agentfile"
)

// DefaultRules returns the standard alert rules generated when alerting is enabled.
func DefaultRules() []agentfile.AlertRule {
	return []agentfile.AlertRule{
		{
			Name:     "agent_down",
			Expr:     "up == 0",
			For:      "1m",
			Severity: "critical",
		},
		{
			Name:     "high_latency_p95",
			Expr:     `histogram_quantile(0.95, rate(http_duration_seconds_bucket[5m])) > 2`,
			For:      "5m",
			Severity: "warning",
		},
		{
			Name:     "high_error_rate",
			Expr:     `rate(http_requests_total{status=~"5.."}[5m]) > 0.1`,
			For:      "5m",
			Severity: "warning",
		},
	}
}

const alertmanagerTemplate = `# Auto-generated by volra — Alertmanager configuration
global:
  resolve_timeout: 5m

route:
  receiver: volra-default
  group_by: ['alertname', 'agent']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h

receivers:
  - name: volra-default
    {{- range .Channels}}
    {{- if eq .Type "slack"}}
    slack_configs:
      - api_url_file: /etc/alertmanager/slack-webhook-url
        channel: '#volra-alerts'
        send_resolved: true
        title: '{{ "{{ .Status | toUpper }}" }}: {{ "{{ .CommonLabels.alertname }}" }}'
        text: 'Agent: {{ "{{ .CommonLabels.agent }}" }}\n{{ "{{ .CommonAnnotations.description }}" }}'
    {{- end}}
    {{- if eq .Type "email"}}
    email_configs:
      - to: '{{.To}}'
        send_resolved: true
    {{- end}}
    {{- if eq .Type "webhook"}}
    webhook_configs:
      - url: '{{.URL}}'
        send_resolved: true
    {{- end}}
    {{- end}}
`

const alertRulesTemplate = `# Auto-generated by volra — Prometheus alert rules
groups:
  - name: volra-agent-alerts
    rules:
{{- range .Rules}}
      - alert: {{.Name}}
        expr: {{.Expr}}
        for: {{.For}}
        labels:
          severity: {{.Severity}}
        annotations:
          description: "{{.Name}} triggered for agent {{ "{{ $labels.instance }}" }}"
{{- end}}
`

// RenderAlertmanagerConfig generates the alertmanager.yml content.
func RenderAlertmanagerConfig(alerts *agentfile.AlertsConfig) (string, error) {
	if alerts == nil || len(alerts.Channels) == 0 {
		return "", fmt.Errorf("no alert channels configured")
	}

	tmpl, err := template.New("alertmanager").Parse(alertmanagerTemplate)
	if err != nil {
		return "", fmt.Errorf("parsing alertmanager template: %w", err)
	}

	var buf strings.Builder
	if err := tmpl.Execute(&buf, alerts); err != nil {
		return "", fmt.Errorf("rendering alertmanager config: %w", err)
	}
	return buf.String(), nil
}

// RenderAlertRules generates the alert-rules.yml content.
// Merges default rules with any custom rules defined in the config.
func RenderAlertRules(alerts *agentfile.AlertsConfig) (string, error) {
	rules := DefaultRules()
	if alerts != nil {
		rules = append(rules, alerts.Rules...)
	}

	// Ensure all rules have defaults.
	for i := range rules {
		if rules[i].For == "" {
			rules[i].For = "5m"
		}
		if rules[i].Severity == "" {
			rules[i].Severity = "warning"
		}
	}

	tmpl, err := template.New("alert-rules").Parse(alertRulesTemplate)
	if err != nil {
		return "", fmt.Errorf("parsing alert rules template: %w", err)
	}

	data := struct{ Rules []agentfile.AlertRule }{Rules: rules}
	var buf strings.Builder
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("rendering alert rules: %w", err)
	}
	return buf.String(), nil
}

// ComposeService returns the docker-compose service definition for Alertmanager.
func ComposeService() map[string]any {
	return map[string]any{
		"image":   "prom/alertmanager:v0.27.0",
		"restart": "unless-stopped",
		"volumes": []string{
			"./alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro",
		},
		"ports": []string{
			"9093:9093",
		},
		"command": []string{
			"--config.file=/etc/alertmanager/alertmanager.yml",
		},
	}
}
