package setup

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/antonioromero/volra/internal/agentfile"
	"github.com/antonioromero/volra/internal/output"
	"github.com/antonioromero/volra/internal/testutil"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func setupProject(t *testing.T, files map[string]string) string {
	t.Helper()
	dir := t.TempDir()
	for name, content := range files {
		path := filepath.Join(dir, name)
		require.NoError(t, os.MkdirAll(filepath.Dir(path), 0755))
		require.NoError(t, os.WriteFile(path, []byte(content), 0644))
	}
	return dir
}

// --- Run() tests ---

func TestRun_GeneratesAgentfile(t *testing.T) {
	dir := setupProject(t, map[string]string{
		"requirements.txt": "fastapi>=0.100.0\n",
		"main.py":          "import os\napp = None\nos.environ[\"API_KEY\"]\n",
	})
	p := &testutil.MockPresenter{}

	err := Run(context.Background(), dir, false, p)
	require.NoError(t, err)

	content, err := os.ReadFile(filepath.Join(dir, "Agentfile"))
	require.NoError(t, err)
	assert.Contains(t, string(content), "version: 1")
	assert.Contains(t, string(content), "framework: generic")
	assert.Contains(t, string(content), "port: 8000")
	assert.Contains(t, string(content), "health_path: /health")
	assert.Contains(t, string(content), "Generated by Volra")
}

func TestRun_GeneratesEnvExample(t *testing.T) {
	dir := setupProject(t, map[string]string{
		"requirements.txt": "requests\n",
		"main.py":          "import os\nos.environ[\"OPENAI_API_KEY\"]\nos.getenv(\"DB_URL\")\n",
	})
	p := &testutil.MockPresenter{}

	err := Run(context.Background(), dir, false, p)
	require.NoError(t, err)

	content, err := os.ReadFile(filepath.Join(dir, ".env.example"))
	require.NoError(t, err)
	text := string(content)
	assert.Contains(t, text, "DB_URL=")
	assert.Contains(t, text, "OPENAI_API_KEY=")
	assert.Contains(t, text, "Volra")
	// No values — just names
	assert.NotContains(t, text, "sk-")
}

func TestRun_NoEnvExampleWhenNoVars(t *testing.T) {
	dir := setupProject(t, map[string]string{
		"requirements.txt": "requests\n",
		"main.py":          "print('hello')\n",
	})
	p := &testutil.MockPresenter{}

	err := Run(context.Background(), dir, false, p)
	require.NoError(t, err)

	_, err = os.Stat(filepath.Join(dir, ".env.example"))
	assert.True(t, os.IsNotExist(err))
}

func TestRun_CreatesGitignore(t *testing.T) {
	dir := setupProject(t, map[string]string{
		"requirements.txt": "requests\n",
		"main.py":          "pass\n",
	})
	p := &testutil.MockPresenter{}

	err := Run(context.Background(), dir, false, p)
	require.NoError(t, err)

	content, err := os.ReadFile(filepath.Join(dir, ".gitignore"))
	require.NoError(t, err)
	assert.Contains(t, string(content), ".volra/")
	assert.Contains(t, string(content), ".env")
}

func TestRun_GitignoreNoDuplicate(t *testing.T) {
	dir := setupProject(t, map[string]string{
		"requirements.txt": "requests\n",
		"main.py":          "pass\n",
		".gitignore":       ".volra/\n.env\n",
	})
	p := &testutil.MockPresenter{}

	err := Run(context.Background(), dir, false, p)
	require.NoError(t, err)

	content, err := os.ReadFile(filepath.Join(dir, ".gitignore"))
	require.NoError(t, err)
	assert.Equal(t, 1, strings.Count(string(content), ".volra/"))
}

func TestRun_GitignoreAppendsNewEntries(t *testing.T) {
	dir := setupProject(t, map[string]string{
		"requirements.txt": "requests\n",
		"main.py":          "pass\n",
		".gitignore":       "__pycache__/\n",
	})
	p := &testutil.MockPresenter{}

	err := Run(context.Background(), dir, false, p)
	require.NoError(t, err)

	content, err := os.ReadFile(filepath.Join(dir, ".gitignore"))
	require.NoError(t, err)
	text := string(content)
	assert.Contains(t, text, "__pycache__/")
	assert.Contains(t, text, ".volra/")
	assert.Contains(t, text, ".env")
}

func TestRun_ExistingAgentfileError(t *testing.T) {
	dir := setupProject(t, map[string]string{
		"requirements.txt": "requests\n",
		"main.py":          "pass\n",
		"Agentfile":        "version: 1\n",
	})
	p := &testutil.MockPresenter{}

	err := Run(context.Background(), dir, false, p)
	require.Error(t, err)
	ue, ok := err.(*output.UserError)
	require.True(t, ok)
	assert.Equal(t, output.CodeAgentfileExists, ue.Code)
	assert.Contains(t, ue.Fix, "--force")
}

func TestRun_ForceOverwrites(t *testing.T) {
	dir := setupProject(t, map[string]string{
		"requirements.txt": "requests\n",
		"main.py":          "pass\n",
		"Agentfile":        "version: 1\nname: old\n",
	})
	p := &testutil.MockPresenter{}

	err := Run(context.Background(), dir, true, p)
	require.NoError(t, err)

	content, err := os.ReadFile(filepath.Join(dir, "Agentfile"))
	require.NoError(t, err)
	assert.Contains(t, string(content), "Generated by Volra")
}

func TestRun_NoPythonProject(t *testing.T) {
	dir := setupProject(t, map[string]string{
		"main.go": "package main\n",
	})
	p := &testutil.MockPresenter{}

	err := Run(context.Background(), dir, false, p)
	require.Error(t, err)
	ue, ok := err.(*output.UserError)
	require.True(t, ok)
	assert.Equal(t, output.CodeNoPythonProject, ue.Code)
}

func TestRun_ReportsResult(t *testing.T) {
	dir := setupProject(t, map[string]string{
		"requirements.txt": "requests\n",
		"main.py":          "pass\n",
	})
	p := &testutil.MockPresenter{}

	err := Run(context.Background(), dir, false, p)
	require.NoError(t, err)

	assert.NotEmpty(t, p.ResultCalls)
	assert.Contains(t, p.ResultCalls[0], "Generated Agentfile")
}

func TestRun_EmitsWarnings(t *testing.T) {
	dir := setupProject(t, map[string]string{
		"requirements.txt": "requests\n",
		"main.py":          "print('no port, no health')\n",
	})
	p := &testutil.MockPresenter{}

	err := Run(context.Background(), dir, false, p)
	require.NoError(t, err)

	// Should have warnings for port and health path defaults
	assert.True(t, len(p.WarnCalls) >= 2, "expected at least 2 warnings, got %d", len(p.WarnCalls))
}

func TestRun_LangGraphDetection(t *testing.T) {
	dir := setupProject(t, map[string]string{
		"requirements.txt": "langgraph>=0.1.0\n",
		"main.py":          "pass\n",
	})
	p := &testutil.MockPresenter{}

	err := Run(context.Background(), dir, false, p)
	require.NoError(t, err)

	content, err := os.ReadFile(filepath.Join(dir, "Agentfile"))
	require.NoError(t, err)
	assert.Contains(t, string(content), "framework: langgraph")
}

// --- deriveName tests ---

func TestDeriveName_Simple(t *testing.T) {
	assert.Equal(t, "my-agent", deriveName("/home/user/my-agent"))
}

func TestDeriveName_Uppercase(t *testing.T) {
	assert.Equal(t, "myagent", deriveName("/home/user/MyAgent"))
}

func TestDeriveName_Spaces(t *testing.T) {
	assert.Equal(t, "my-project", deriveName("/home/user/My Project"))
}

func TestDeriveName_SpecialChars(t *testing.T) {
	assert.Equal(t, "my-agent-v2", deriveName("/home/user/my_agent_v2"))
}

func TestDeriveName_Short(t *testing.T) {
	assert.Equal(t, "my-agent", deriveName("/x"))
}

func TestDeriveName_Long(t *testing.T) {
	long := "/home/user/" + strings.Repeat("a", 100)
	name := deriveName(long)
	assert.LessOrEqual(t, len(name), 63)
}

// --- isPythonProject tests ---

func TestIsPythonProject_Requirements(t *testing.T) {
	dir := setupProject(t, map[string]string{"requirements.txt": "flask\n"})
	assert.True(t, isPythonProject(dir))
}

func TestIsPythonProject_Pyproject(t *testing.T) {
	dir := setupProject(t, map[string]string{"pyproject.toml": "[project]\n"})
	assert.True(t, isPythonProject(dir))
}

func TestIsPythonProject_None(t *testing.T) {
	dir := setupProject(t, map[string]string{"main.go": "package main\n"})
	assert.False(t, isPythonProject(dir))
}

// --- writeAgentfile tests ---

func TestWriteAgentfile_IncludesComments(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "Agentfile")
	af := &agentfile.Agentfile{
		Version: 1, Name: "test", Framework: agentfile.FrameworkGeneric,
		Port: 8000, HealthPath: "/health", Dockerfile: agentfile.DockerfileModeAuto,
	}
	require.NoError(t, writeAgentfile(path, af))

	content, err := os.ReadFile(path)
	require.NoError(t, err)
	text := string(content)
	assert.Contains(t, text, "# generic | langgraph")
	assert.Contains(t, text, "# auto | custom")
}

func TestWriteAgentfile_WithEnv(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "Agentfile")
	af := &agentfile.Agentfile{
		Version: 1, Name: "test", Framework: agentfile.FrameworkGeneric,
		Port: 8000, HealthPath: "/health",
		Env:        []string{"KEY_A", "KEY_B"},
		Dockerfile: agentfile.DockerfileModeAuto,
	}
	require.NoError(t, writeAgentfile(path, af))

	content, err := os.ReadFile(path)
	require.NoError(t, err)
	text := string(content)
	assert.Contains(t, text, "  - KEY_A")
	assert.Contains(t, text, "  - KEY_B")
}

// --- writeEnvExample tests ---

func TestWriteEnvExample_Format(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, ".env.example")
	require.NoError(t, writeEnvExample(path, []string{"API_KEY", "DB_URL"}))

	content, err := os.ReadFile(path)
	require.NoError(t, err)
	text := string(content)
	assert.Contains(t, text, "API_KEY=")
	assert.Contains(t, text, "DB_URL=")
	assert.Contains(t, text, "Copy this file")
}

// --- updateGitignore tests ---

func TestUpdateGitignore_CreatesNew(t *testing.T) {
	dir := t.TempDir()
	require.NoError(t, updateGitignore(dir))

	content, err := os.ReadFile(filepath.Join(dir, ".gitignore"))
	require.NoError(t, err)
	text := string(content)
	assert.Contains(t, text, ".volra/")
	assert.Contains(t, text, ".env")
}

func TestUpdateGitignore_AppendsToExisting(t *testing.T) {
	dir := t.TempDir()
	require.NoError(t, os.WriteFile(filepath.Join(dir, ".gitignore"), []byte("*.pyc\n"), 0644))
	require.NoError(t, updateGitignore(dir))

	content, err := os.ReadFile(filepath.Join(dir, ".gitignore"))
	require.NoError(t, err)
	text := string(content)
	assert.Contains(t, text, "*.pyc")
	assert.Contains(t, text, ".volra/")
}

func TestUpdateGitignore_NoDuplicate(t *testing.T) {
	dir := t.TempDir()
	require.NoError(t, os.WriteFile(filepath.Join(dir, ".gitignore"), []byte(".volra/\n.env\n"), 0644))
	require.NoError(t, updateGitignore(dir))

	content, err := os.ReadFile(filepath.Join(dir, ".gitignore"))
	require.NoError(t, err)
	assert.Equal(t, 1, strings.Count(string(content), ".volra/"))
	assert.Equal(t, 1, strings.Count(string(content), ".env"))
}
