// Package setup implements the volra init command logic.
package setup

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/romerox3/volra/internal/agentfile"
	"github.com/romerox3/volra/internal/output"
)

var sanitizeRegex = regexp.MustCompile(`[^a-z0-9-]`)

// Run executes the init command pipeline: scan, detect, generate, write.
func Run(_ context.Context, dir string, force bool, p output.Presenter) error {
	absDir, err := filepath.Abs(dir)
	if err != nil {
		return fmt.Errorf("resolving path: %w", err)
	}

	agentfilePath := filepath.Join(absDir, "Agentfile")

	if !force {
		if _, err := os.Stat(agentfilePath); err == nil {
			return &output.UserError{
				Code: output.CodeAgentfileExists,
				What: "Agentfile already exists",
				Fix:  "Use --force to overwrite",
			}
		}
	}

	if !isPythonProject(absDir) {
		return &output.UserError{
			Code: output.CodeNoPythonProject,
			What: "No Python project detected",
			Fix:  "Volra requires requirements.txt, pyproject.toml, or Pipfile in the project directory",
		}
	}

	p.Progress("Scanning project...")

	result := ScanProject(absDir)

	for _, w := range result.Warnings {
		p.Warn(w)
	}

	name := deriveName(absDir)

	af := &agentfile.Agentfile{
		Version:        1,
		Name:           name,
		Framework:      result.Framework,
		Port:           result.Port,
		HealthPath:     result.HealthPath,
		Env:            result.EnvVars,
		PackageManager: result.PackageManager,
		Dockerfile:     agentfile.DockerfileModeAuto,
	}

	if err := writeAgentfile(agentfilePath, af); err != nil {
		return fmt.Errorf("writing Agentfile: %w", err)
	}

	if len(result.EnvVars) > 0 {
		envPath := filepath.Join(absDir, ".env.example")
		if err := writeEnvExample(envPath, result.EnvVars); err != nil {
			return fmt.Errorf("writing .env.example: %w", err)
		}
	}

	if err := updateGitignore(absDir); err != nil {
		return fmt.Errorf("updating .gitignore: %w", err)
	}

	p.Result(fmt.Sprintf("Generated Agentfile for %s", name))
	return nil
}

// isPythonProject checks for Python dependency files.
func isPythonProject(dir string) bool {
	for _, f := range []string{"requirements.txt", "pyproject.toml", "Pipfile"} {
		if _, err := os.Stat(filepath.Join(dir, f)); err == nil {
			return true
		}
	}
	return false
}

// deriveName converts a directory name to a valid DNS label.
func deriveName(dir string) string {
	base := filepath.Base(dir)
	name := strings.ToLower(base)
	name = sanitizeRegex.ReplaceAllString(name, "-")
	name = strings.Trim(name, "-")
	if name == "" || len(name) < 2 {
		name = "my-agent"
	}
	if len(name) > 63 {
		name = name[:63]
		name = strings.TrimRight(name, "-")
	}
	return name
}

// writeAgentfile writes an Agentfile with inline comments.
func writeAgentfile(path string, af *agentfile.Agentfile) error {
	var b strings.Builder
	b.WriteString("# Generated by Volra — edit freely, this is your configuration\n")
	fmt.Fprintf(&b, "version: %d\n\n", af.Version)
	fmt.Fprintf(&b, "name: %s\n", af.Name)
	fmt.Fprintf(&b, "framework: %s          # generic | langgraph | crewai\n", af.Framework)
	fmt.Fprintf(&b, "port: %d\n", af.Port)
	fmt.Fprintf(&b, "health_path: %s\n", af.HealthPath)

	if af.PackageManager != "" && af.PackageManager != agentfile.PackageManagerPip {
		fmt.Fprintf(&b, "package_manager: %s     # pip | poetry | uv | pipenv\n", af.PackageManager)
	}

	if len(af.Env) > 0 {
		b.WriteString("env:\n")
		for _, e := range af.Env {
			fmt.Fprintf(&b, "  - %s\n", e)
		}
	}

	fmt.Fprintf(&b, "dockerfile: %s            # auto | custom\n", af.Dockerfile)

	return os.WriteFile(path, []byte(b.String()), 0644)
}

// writeEnvExample writes a .env.example file with variable names only.
func writeEnvExample(path string, vars []string) error {
	var b strings.Builder
	b.WriteString("# Volra — Environment Variables\n")
	b.WriteString("# Copy this file to .env and fill in the values\n")
	b.WriteString("# Values are injected into your agent container at deploy time\n\n")
	for _, v := range vars {
		b.WriteString(v + "=\n")
	}
	return os.WriteFile(path, []byte(b.String()), 0644)
}

// updateGitignore adds .volra/ and .env entries to .gitignore without duplicating.
func updateGitignore(dir string) error {
	path := filepath.Join(dir, ".gitignore")
	entries := []string{".volra/", ".env"}

	existing, err := os.ReadFile(path)
	if err != nil && !os.IsNotExist(err) {
		return err
	}

	lines := strings.Split(string(existing), "\n")
	lineSet := make(map[string]bool)
	for _, l := range lines {
		lineSet[strings.TrimSpace(l)] = true
	}

	var toAdd []string
	for _, entry := range entries {
		if !lineSet[entry] {
			toAdd = append(toAdd, entry)
		}
	}

	if len(toAdd) == 0 {
		return nil
	}

	f, err := os.OpenFile(path, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
	if err != nil {
		return err
	}
	defer func() { _ = f.Close() }()

	content := string(existing)
	if len(content) > 0 && !strings.HasSuffix(content, "\n") {
		if _, err := f.WriteString("\n"); err != nil {
			return err
		}
	}

	for _, entry := range toAdd {
		if _, err := f.WriteString(entry + "\n"); err != nil {
			return err
		}
	}
	return nil
}
