// Package compliance generates EU AI Act compliance documentation templates.
package compliance

import (
	"fmt"
	"strings"
	"text/template"
	"time"

	"github.com/romerox3/volra/internal/agentfile"
	"github.com/romerox3/volra/internal/alerting"
)

const complianceTemplate = `# EU AI Act Compliance Documentation

**Agent:** {{.Name}}
**Framework:** {{.Framework}}
**Generated:** {{.Date}}
**Version:** {{.Version}}

---

## 1. System Description

| Field | Value |
|-------|-------|
| Agent Name | {{.Name}} |
| Framework | {{.Framework}} |
| Health Endpoint | {{.HealthPath}} |
| Port | {{.Port}} |

### Purpose and Intended Use

> _Describe the purpose of this AI agent and its intended use cases._

### Risk Classification

> _Classify this agent under the EU AI Act risk categories: Unacceptable / High / Limited / Minimal._

---

## 2. Data Governance

### Training Data

> _Describe the training data used, including sources, quality measures, and any biases identified._

### Input Data

> _Describe what data the agent processes at runtime._

### Data Retention

> _Describe data retention policies and deletion procedures._

---

## 3. Technical Documentation

### Architecture

- **Deployment:** Docker Compose (self-hosted)
- **Monitoring:** Prometheus + Grafana
{{- if .HasObservability}}
- **Observability Level:** {{.ObservabilityLevel}}
{{- end}}
{{- if .HasAlerting}}
- **Alerting:** Alertmanager ({{.AlertChannels}})
{{- end}}

### Performance Metrics

> _Document key performance metrics and their acceptable ranges._

---

## 4. Human Oversight

{{- if .HasAlerting}}

### Automated Alerting

The following alert rules are configured:

{{range .AlertRules}}- **{{.Name}}**: ` + "`{{.Expr}}`" + ` (severity: {{.Severity}}, for: {{.For}})
{{end}}
{{- else}}

> _No automated alerting configured. Consider adding alerts for human oversight._
> _Run: Add an ` + "`alerts`" + ` section to your Agentfile._

{{- end}}

### Monitoring Dashboard

{{- if .HasObservability}}
- Grafana dashboard available at deployment
- Health endpoint: {{.HealthPath}}
{{- else}}
> _Configure observability in your Agentfile for monitoring capabilities._
{{- end}}

---

## 5. Transparency

### User Notification

> _Describe how users are informed they are interacting with an AI system._

### Explainability

> _Describe how the agent's decisions can be explained to users._

---

## 6. Record Keeping

- Deployment audit log: ` + "`.volra/audit.log`" + `
- Prometheus metrics retained for 7 days (default)
{{- if .HasObservability}}
- LLM execution traces available via observability stack
{{- end}}

---

## 7. Conformity Assessment

> _Document any conformity assessments performed._

### Checklist

- [ ] Risk classification completed
- [ ] Training data documented
- [ ] Human oversight mechanisms in place
- [ ] Transparency requirements met
- [ ] Technical documentation complete
- [ ] Record keeping configured
- [ ] Regular review schedule established

---

*This document was auto-generated by Volra. Complete all sections marked with > before submission.*
`

// ComplianceData holds the template data for compliance doc generation.
type ComplianceData struct {
	Name               string
	Framework          string
	Date               string
	Version            int
	HealthPath         string
	Port               int
	HasObservability   bool
	ObservabilityLevel int
	HasAlerting        bool
	AlertChannels      string
	AlertRules         []agentfile.AlertRule
}

// Generate creates a compliance Markdown document from an Agentfile.
func Generate(af *agentfile.Agentfile) (string, error) {
	if af == nil {
		return "", fmt.Errorf("no Agentfile provided")
	}

	data := ComplianceData{
		Name:       af.Name,
		Framework:  string(af.Framework),
		Date:       time.Now().UTC().Format("2006-01-02"),
		Version:    af.Version,
		HealthPath: af.HealthPath,
		Port:       af.Port,
	}

	if af.Observability != nil {
		data.HasObservability = true
		data.ObservabilityLevel = af.Observability.Level
		if data.ObservabilityLevel == 0 {
			data.ObservabilityLevel = 1
		}
	}

	if af.Alerts != nil && len(af.Alerts.Channels) > 0 {
		data.HasAlerting = true
		var channels []string
		for _, ch := range af.Alerts.Channels {
			channels = append(channels, ch.Type)
		}
		data.AlertChannels = strings.Join(channels, ", ")

		// Include default + custom rules for complete documentation.
		data.AlertRules = append(alerting.DefaultRules(), af.Alerts.Rules...)
	}

	tmpl, err := template.New("compliance").Parse(complianceTemplate)
	if err != nil {
		return "", fmt.Errorf("parsing compliance template: %w", err)
	}

	var buf strings.Builder
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("rendering compliance doc: %w", err)
	}

	return buf.String(), nil
}
