package deploy

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/antonioromero/volra/internal/agentfile"
	"github.com/antonioromero/volra/internal/testutil"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestRenderDockerfile_WithRequirements(t *testing.T) {
	tc := &TemplateContext{
		Agentfile: agentfile.Agentfile{
			Version: 1, Name: "my-agent", Framework: agentfile.FrameworkGeneric,
			Port: 8000, HealthPath: "/health", Dockerfile: agentfile.DockerfileModeAuto,
		},
		PythonVersion:   "3.11",
		EntryPoint:      "main.py",
		HasRequirements: true,
	}
	got, err := RenderDockerfile(tc)
	require.NoError(t, err)
	testutil.AssertGolden(t, got, filepath.Join("testdata", "golden", "dockerfile_requirements.golden"))
}

func TestRenderDockerfile_WithPyproject(t *testing.T) {
	tc := &TemplateContext{
		Agentfile: agentfile.Agentfile{
			Version: 1, Name: "my-agent", Framework: agentfile.FrameworkLangGraph,
			Port: 9000, HealthPath: "/healthz", Dockerfile: agentfile.DockerfileModeAuto,
		},
		PythonVersion:   "3.12",
		EntryPoint:      "app.py",
		HasRequirements: false,
	}
	got, err := RenderDockerfile(tc)
	require.NoError(t, err)
	testutil.AssertGolden(t, got, filepath.Join("testdata", "golden", "dockerfile_pyproject.golden"))
}

func TestRenderDockerfile_CustomPort(t *testing.T) {
	tc := &TemplateContext{
		Agentfile: agentfile.Agentfile{
			Version: 1, Name: "test", Framework: agentfile.FrameworkGeneric,
			Port: 3000, HealthPath: "/health", Dockerfile: agentfile.DockerfileModeAuto,
		},
		PythonVersion:   "3.11",
		EntryPoint:      "server.py",
		HasRequirements: true,
	}
	got, err := RenderDockerfile(tc)
	require.NoError(t, err)
	assert.Contains(t, got, "EXPOSE 3000")
	assert.Contains(t, got, `CMD ["python", "server.py"]`)
}

func TestGenerateDockerfile_WritesFile(t *testing.T) {
	dir := t.TempDir()
	tc := &TemplateContext{
		Agentfile: agentfile.Agentfile{
			Version: 1, Name: "test", Framework: agentfile.FrameworkGeneric,
			Port: 8000, HealthPath: "/health", Dockerfile: agentfile.DockerfileModeAuto,
		},
		PythonVersion:   "3.11",
		EntryPoint:      "main.py",
		HasRequirements: true,
	}
	err := GenerateDockerfile(tc, dir)
	require.NoError(t, err)

	content, err := os.ReadFile(filepath.Join(dir, OutputDir, "Dockerfile"))
	require.NoError(t, err)
	assert.Contains(t, string(content), "FROM python:3.11-slim")
	assert.Contains(t, string(content), "Generated by Volra")
}

func TestGenerateDockerfile_CreatesOutputDir(t *testing.T) {
	dir := t.TempDir()
	tc := &TemplateContext{
		Agentfile: agentfile.Agentfile{
			Version: 1, Name: "test", Framework: agentfile.FrameworkGeneric,
			Port: 8000, HealthPath: "/health", Dockerfile: agentfile.DockerfileModeAuto,
		},
		PythonVersion:   "3.11",
		EntryPoint:      "main.py",
		HasRequirements: true,
	}
	err := GenerateDockerfile(tc, dir)
	require.NoError(t, err)

	info, err := os.Stat(filepath.Join(dir, OutputDir))
	require.NoError(t, err)
	assert.True(t, info.IsDir())
}

// --- BuildContext tests ---

func TestBuildContext_WithRequirements(t *testing.T) {
	dir := t.TempDir()
	require.NoError(t, os.WriteFile(filepath.Join(dir, "requirements.txt"), []byte("flask\n"), 0644))
	require.NoError(t, os.WriteFile(filepath.Join(dir, "main.py"), []byte("pass\n"), 0644))

	af := &agentfile.Agentfile{
		Version: 1, Name: "test", Framework: agentfile.FrameworkGeneric,
		Port: 8000, HealthPath: "/health", Dockerfile: agentfile.DockerfileModeAuto,
	}
	tc := BuildContext(af, dir)
	assert.True(t, tc.HasRequirements)
	assert.Equal(t, "main.py", tc.EntryPoint)
	assert.Equal(t, "3.11", tc.PythonVersion) // fallback
}

func TestBuildContext_WithPyproject(t *testing.T) {
	dir := t.TempDir()
	require.NoError(t, os.WriteFile(filepath.Join(dir, "pyproject.toml"), []byte("[project]\nrequires-python = \">=3.12\"\n"), 0644))
	require.NoError(t, os.WriteFile(filepath.Join(dir, "app.py"), []byte("pass\n"), 0644))

	af := &agentfile.Agentfile{
		Version: 1, Name: "test", Framework: agentfile.FrameworkGeneric,
		Port: 8000, HealthPath: "/health", Dockerfile: agentfile.DockerfileModeAuto,
	}
	tc := BuildContext(af, dir)
	assert.False(t, tc.HasRequirements)
	assert.Equal(t, "app.py", tc.EntryPoint)
	assert.Equal(t, "3.12", tc.PythonVersion)
}

func TestBuildContext_FallbackDefaults(t *testing.T) {
	dir := t.TempDir()

	af := &agentfile.Agentfile{
		Version: 1, Name: "test", Framework: agentfile.FrameworkGeneric,
		Port: 8000, HealthPath: "/health", Dockerfile: agentfile.DockerfileModeAuto,
	}
	tc := BuildContext(af, dir)
	assert.False(t, tc.HasRequirements)
	assert.Equal(t, "main.py", tc.EntryPoint) // fallback
	assert.Equal(t, "3.11", tc.PythonVersion) // fallback
}

func TestBuildContext_EntryPointPriority(t *testing.T) {
	dir := t.TempDir()
	require.NoError(t, os.WriteFile(filepath.Join(dir, "app.py"), []byte("pass\n"), 0644))
	require.NoError(t, os.WriteFile(filepath.Join(dir, "server.py"), []byte("pass\n"), 0644))

	af := &agentfile.Agentfile{
		Version: 1, Name: "test", Framework: agentfile.FrameworkGeneric,
		Port: 8000, HealthPath: "/health", Dockerfile: agentfile.DockerfileModeAuto,
	}
	tc := BuildContext(af, dir)
	assert.Equal(t, "app.py", tc.EntryPoint) // app.py before server.py
}

// --- detectPythonVersion tests ---

func TestDetectPythonVersion_FromPyproject(t *testing.T) {
	dir := t.TempDir()
	require.NoError(t, os.WriteFile(filepath.Join(dir, "pyproject.toml"),
		[]byte("[project]\nrequires-python = \">=3.10\"\n"), 0644))
	assert.Equal(t, "3.10", detectPythonVersion(dir))
}

func TestDetectPythonVersion_Fallback(t *testing.T) {
	dir := t.TempDir()
	assert.Equal(t, "3.11", detectPythonVersion(dir))
}

func TestDetectPythonVersion_NoRequiresPython(t *testing.T) {
	dir := t.TempDir()
	require.NoError(t, os.WriteFile(filepath.Join(dir, "pyproject.toml"),
		[]byte("[project]\nname = \"test\"\n"), 0644))
	assert.Equal(t, "3.11", detectPythonVersion(dir))
}
