package deploy

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/antonioromero/volra/internal/agentfile"
	"github.com/antonioromero/volra/internal/testutil"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestRenderPrometheus_Minimal(t *testing.T) {
	tc := &TemplateContext{
		Agentfile: agentfile.Agentfile{
			Version: 1, Name: "my-agent", Framework: agentfile.FrameworkGeneric,
			Port: 8000, HealthPath: "/health", Dockerfile: agentfile.DockerfileModeAuto,
		},
		PythonVersion:   "3.11",
		EntryPoint:      "main.py",
		HasRequirements: true,
	}
	got, err := RenderPrometheus(tc)
	require.NoError(t, err)
	testutil.AssertGolden(t, got, filepath.Join("testdata", "golden", "prometheus_minimal.golden"))
}

func TestRenderPrometheus_CustomPort(t *testing.T) {
	tc := &TemplateContext{
		Agentfile: agentfile.Agentfile{
			Version: 1, Name: "test", Framework: agentfile.FrameworkGeneric,
			Port: 9000, HealthPath: "/healthz", Dockerfile: agentfile.DockerfileModeAuto,
		},
		PythonVersion:   "3.12",
		EntryPoint:      "app.py",
		HasRequirements: true,
	}
	got, err := RenderPrometheus(tc)
	require.NoError(t, err)
	testutil.AssertGolden(t, got, filepath.Join("testdata", "golden", "prometheus_custom_port.golden"))
}

func TestRenderPrometheus_ScrapeInterval(t *testing.T) {
	tc := &TemplateContext{
		Agentfile: agentfile.Agentfile{
			Version: 1, Name: "test", Framework: agentfile.FrameworkGeneric,
			Port: 8000, HealthPath: "/health", Dockerfile: agentfile.DockerfileModeAuto,
		},
		PythonVersion:   "3.11",
		EntryPoint:      "main.py",
		HasRequirements: true,
	}
	got, err := RenderPrometheus(tc)
	require.NoError(t, err)
	assert.Contains(t, got, "scrape_interval: 15s")
	assert.Contains(t, got, "scrape_timeout: 10s")
}

func TestRenderPrometheus_RuleFiles(t *testing.T) {
	tc := &TemplateContext{
		Agentfile: agentfile.Agentfile{
			Version: 1, Name: "test", Framework: agentfile.FrameworkGeneric,
			Port: 8000, HealthPath: "/health", Dockerfile: agentfile.DockerfileModeAuto,
		},
		PythonVersion:   "3.11",
		EntryPoint:      "main.py",
		HasRequirements: true,
	}
	got, err := RenderPrometheus(tc)
	require.NoError(t, err)
	assert.Contains(t, got, "/etc/prometheus/alert_rules.yml")
}

func TestRenderPrometheus_TwoScrapeJobs(t *testing.T) {
	tc := &TemplateContext{
		Agentfile: agentfile.Agentfile{
			Version: 1, Name: "test", Framework: agentfile.FrameworkGeneric,
			Port: 8000, HealthPath: "/health", Dockerfile: agentfile.DockerfileModeAuto,
		},
		PythonVersion:   "3.11",
		EntryPoint:      "main.py",
		HasRequirements: true,
	}
	got, err := RenderPrometheus(tc)
	require.NoError(t, err)
	assert.Contains(t, got, "job_name: agent-health")
	assert.Contains(t, got, "job_name: agent-metrics")
}

func TestRenderPrometheus_HealthJobTarget(t *testing.T) {
	tc := &TemplateContext{
		Agentfile: agentfile.Agentfile{
			Version: 1, Name: "test", Framework: agentfile.FrameworkGeneric,
			Port: 3000, HealthPath: "/healthz", Dockerfile: agentfile.DockerfileModeAuto,
		},
		PythonVersion:   "3.11",
		EntryPoint:      "main.py",
		HasRequirements: true,
	}
	got, err := RenderPrometheus(tc)
	require.NoError(t, err)
	assert.Contains(t, got, "http://agent:3000/healthz")
	assert.Contains(t, got, "metrics_path: /probe")
	assert.Contains(t, got, "blackbox:9115")
}

func TestRenderPrometheus_MetricsJobTarget(t *testing.T) {
	tc := &TemplateContext{
		Agentfile: agentfile.Agentfile{
			Version: 1, Name: "test", Framework: agentfile.FrameworkGeneric,
			Port: 8000, HealthPath: "/health", Dockerfile: agentfile.DockerfileModeAuto,
		},
		PythonVersion:   "3.11",
		EntryPoint:      "main.py",
		HasRequirements: true,
	}
	got, err := RenderPrometheus(tc)
	require.NoError(t, err)
	assert.Contains(t, got, "metrics_path: /metrics")
}

func TestGeneratePrometheus_WritesFile(t *testing.T) {
	dir := t.TempDir()
	tc := &TemplateContext{
		Agentfile: agentfile.Agentfile{
			Version: 1, Name: "test", Framework: agentfile.FrameworkGeneric,
			Port: 8000, HealthPath: "/health", Dockerfile: agentfile.DockerfileModeAuto,
		},
		PythonVersion:   "3.11",
		EntryPoint:      "main.py",
		HasRequirements: true,
	}
	err := GeneratePrometheus(tc, dir)
	require.NoError(t, err)

	content, err := os.ReadFile(filepath.Join(dir, OutputDir, "prometheus.yml"))
	require.NoError(t, err)
	assert.Contains(t, string(content), "Generated by Volra")
	assert.Contains(t, string(content), "agent-health")
}

func TestCopyAlertRules_WritesFile(t *testing.T) {
	dir := t.TempDir()
	err := CopyAlertRules(dir)
	require.NoError(t, err)

	content, err := os.ReadFile(filepath.Join(dir, OutputDir, "alert_rules.yml"))
	require.NoError(t, err)
	assert.Contains(t, string(content), "AgentDown")
	assert.Contains(t, string(content), `probe_success{job="agent-health"} == 0`)
	assert.Contains(t, string(content), "for: 1m")
}

func TestCopyAlertRules_CreatesOutputDir(t *testing.T) {
	dir := t.TempDir()
	err := CopyAlertRules(dir)
	require.NoError(t, err)

	info, err := os.Stat(filepath.Join(dir, OutputDir))
	require.NoError(t, err)
	assert.True(t, info.IsDir())
}

func TestCopyAlertRules_StaticContent(t *testing.T) {
	dir := t.TempDir()
	err := CopyAlertRules(dir)
	require.NoError(t, err)

	content, err := os.ReadFile(filepath.Join(dir, OutputDir, "alert_rules.yml"))
	require.NoError(t, err)
	assert.Contains(t, string(content), "severity: critical")
	assert.Contains(t, string(content), "volra-agent")
}

func TestCopyBlackboxConfig_WritesFile(t *testing.T) {
	dir := t.TempDir()
	err := CopyBlackboxConfig(dir)
	require.NoError(t, err)

	content, err := os.ReadFile(filepath.Join(dir, OutputDir, "blackbox.yml"))
	require.NoError(t, err)
	assert.Contains(t, string(content), "http_2xx")
	assert.Contains(t, string(content), "prober: http")
}
