package otel

import (
	"fmt"
	"strings"
	"text/template"
)

// CollectorConfig holds the parameters for generating an OTel Collector configuration.
type CollectorConfig struct {
	// PrometheusPort is the port where the collector exposes Prometheus metrics.
	PrometheusPort int
	// Agents is the list of instrumented agent service names.
	Agents []string
}

const collectorConfigTemplate = `# Auto-generated by volra — OTel Collector configuration
receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4318"

processors:
  batch:
    timeout: 5s
    send_batch_size: 256

exporters:
  prometheus:
    endpoint: "0.0.0.0:{{.PrometheusPort}}"
    namespace: volra
    resource_to_telemetry_conversion:
      enabled: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
`

// RenderCollectorConfig generates the OTel Collector YAML configuration.
func RenderCollectorConfig(cfg CollectorConfig) (string, error) {
	if cfg.PrometheusPort == 0 {
		cfg.PrometheusPort = 8889
	}

	tmpl, err := template.New("otel-collector").Parse(collectorConfigTemplate)
	if err != nil {
		return "", fmt.Errorf("parsing collector config template: %w", err)
	}

	var buf strings.Builder
	if err := tmpl.Execute(&buf, cfg); err != nil {
		return "", fmt.Errorf("rendering collector config: %w", err)
	}
	return buf.String(), nil
}

// ComposeService returns the docker-compose service definition for the OTel Collector.
func ComposeService(prometheusPort int) map[string]any {
	if prometheusPort == 0 {
		prometheusPort = 8889
	}
	return map[string]any{
		"image":   "otel/opentelemetry-collector-contrib:0.98.0",
		"restart": "unless-stopped",
		"volumes": []string{
			"./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml:ro",
		},
		"ports": []string{
			"4318:4318",
			fmt.Sprintf("%d:%d", prometheusPort, prometheusPort),
		},
	}
}
