// Package otel provides auto-instrumentation support for Python agent containers.
// It generates OTel wrapper scripts and collector configurations.
package otel

import (
	"fmt"
	"strings"
	"text/template"
)

// WrapperConfig holds the parameters for generating an OTel wrapper entrypoint.
type WrapperConfig struct {
	// OriginalEntrypoint is the agent's original command (e.g. "python main.py").
	OriginalEntrypoint string
	// ServiceName is the OpenTelemetry service name (typically the agent name).
	ServiceName string
	// CollectorEndpoint is the OTel Collector OTLP endpoint (e.g. "http://otel-collector:4318").
	CollectorEndpoint string
}

const wrapperTemplate = `#!/bin/sh
# Auto-generated by volra — OTel auto-instrumentation wrapper
# This wraps the agent entrypoint with OpenTelemetry instrumentation.

export OTEL_SERVICE_NAME="{{.ServiceName}}"
export OTEL_EXPORTER_OTLP_ENDPOINT="{{.CollectorEndpoint}}"
export OTEL_EXPORTER_OTLP_PROTOCOL="http/protobuf"
export OTEL_TRACES_EXPORTER="otlp"
export OTEL_METRICS_EXPORTER="otlp"
export OTEL_LOGS_EXPORTER="none"

# Install opentelemetry-instrument if not already available
if ! command -v opentelemetry-instrument >/dev/null 2>&1; then
  pip install --quiet opentelemetry-distro opentelemetry-exporter-otlp 2>/dev/null
  opentelemetry-bootstrap -a install 2>/dev/null
fi

exec opentelemetry-instrument {{.OriginalEntrypoint}}
`

// RenderWrapper generates the OTel wrapper shell script.
func RenderWrapper(cfg WrapperConfig) (string, error) {
	tmpl, err := template.New("otel-wrapper").Parse(wrapperTemplate)
	if err != nil {
		return "", fmt.Errorf("parsing otel wrapper template: %w", err)
	}

	var buf strings.Builder
	if err := tmpl.Execute(&buf, cfg); err != nil {
		return "", fmt.Errorf("rendering otel wrapper: %w", err)
	}
	return buf.String(), nil
}

// DockerfileSnippet returns the Dockerfile lines to inject the OTel wrapper.
// This is appended to the existing Dockerfile during deploy when auto-instrumentation is enabled.
func DockerfileSnippet(originalCmd string) string {
	return fmt.Sprintf(`# --- OTel auto-instrumentation ---
COPY .volra/otel-wrapper.sh /usr/local/bin/otel-wrapper.sh
RUN chmod +x /usr/local/bin/otel-wrapper.sh
RUN pip install --quiet opentelemetry-distro opentelemetry-exporter-otlp && \
    opentelemetry-bootstrap -a install
ENTRYPOINT ["/usr/local/bin/otel-wrapper.sh"]
CMD [%q]
`, originalCmd)
}
